# Generated by Django 5.2 on 2025-04-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('language', models.CharField(blank=True, default='English', max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
    ]
